version: '3'
services:
  arc72-indexer-backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: xarmian/arc72-indexer-backend
    container_name: arc72-indexer-backend
    volumes:
      - ./db:/app/db
    restart: unless-stopped
